# TÂCHE LIÉE : TT-16 (Orchestration de l'API et du LLM)
services:
  api:
    build: .
    container_name: cyber_api
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama

  
  ollama:
    image: ollama/ollama:latest
    container_name: cyber_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data